# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    enable_automatic_code_signing
    git_pull
    increment_build_number(xcodeproj: "Icro.xcodeproj")
    build_app(workspace: "Icro.xcworkspace", scheme: "Icro")
    upload_to_testflight(skip_submission: true)
    sh("git", "commit", "-m", "Bump version number")
    sh("git", "push")
  end
end
