# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run unit tests"
  lane :tests do
    run_tests(workspace: "Icro.xcworkspace",
              derived_data_path: "derivedData",
              devices: ["iPhone Xs"],
              scheme: "Icro")
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    enable_automatic_code_signing
    git_pull
    increment_build_number(xcodeproj: "Icro.xcodeproj")
    build_app(workspace: "Icro.xcworkspace", scheme: "Icro")
    upload_to_testflight(skip_waiting_for_build_processing: true)
    sh("git", "commit", "-a", "-m", "Bump version number")
    sh("git", "push")
  end

  lane :bump_version do
    increment_build_number(xcodeproj: "Icro.xcodeproj")
  end

  lane :beta_ci do
    match(type: "development", readonly: true)
    match(type: "appstore", readonly: true)
    build_app(workspace: "Icro.xcworkspace", scheme: "Icro")
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end
end
