# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run unit tests"
  lane :tests do
    run_tests(workspace: "Icro.xcworkspace",
              derived_data_path: "derivedData",
              devices: ["iPhone 11"],
              scheme: "Icro",
              xcargs: "-testPlan Icro")
  end

  lane :bump_version do
    build_number = number_of_commits(all: true)
    increment_build_number(build_number: build_number)
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    bump_version
    enable_automatic_code_signing
    git_pull
    increment_build_number(xcodeproj: "Icro.xcodeproj")
    build_app(workspace: "Icro.xcworkspace", scheme: "Icro")
    upload_to_testflight(skip_waiting_for_build_processing: true)
    sh("git", "commit", "-a", "-m", "Bump version number")
    sh("git", "push")
  end

  lane :beta_ci do
    bump_version
    create_keychain(
      name: "Fastlane_CI",
      password: "CI_Password",
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      add_to_search_list: true,
    )
    match(type: "development", readonly: true, keychain_name: 'Fastlane_CI', keychain_password: 'CI_Password')
    match(type: "appstore", readonly: true, keychain_name: 'Fastlane_CI', keychain_password: 'CI_Password')
    build_app(workspace: "Icro.xcworkspace", scheme: "Icro")
    upload_to_testflight(skip_waiting_for_build_processing: true, username: "icro@hartl.co")
  end
end
