# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  "iPhone Xs Max",
  "iPad Pro (12.9-inch) (3rd generation)",
])

languages([
  "en-US",
])
