name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: submodules-init
      uses: snickerbockers/submodules-init@v4
    - name: Bundle Install
      run: bundle install
    - name: Install Danger
      run: brew install danger/tap/danger-js 
    - name: Run Danger
      run: danger ci
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and test
      run: bundle exec fastlane tests
